[package]
name = "schmargs"
version = "0.0.0"
edition = "2021"

[lints.rust]
missing_docs = "warn"

[dependencies]
schmargs-derive = { version = "0.0.0", path = "../schmargs-derive" }

[features]
default = ["std"]
std = ["schmargs-derive/std"]
